version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "${SERVER_PORT:-5000}:5000"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}
    container_name: frontend
    restart: always
    ports:
      - "${CLIENT_PORT:-3000}:80"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - server

volumes:
  mongo_data:
